version: 2.1

orbs:
  slack: circleci/slack@4.4.2

jobs:
  build:
    machine:
      image: ubuntu-1604:202104-01
    steps:
      - checkout
      - run:
          name: Update Packages
          command: sudo apt-get update
      - run:
          name: Install Required Packages
          command: sudo apt-get install daemontools
      - run:
          name: Run Tests
          command: make check
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  build-and-notify:
    jobs:
      - build:
          context:
            - slack
