version: 2.1

orbs:
  slack: circleci/slack@4.4.2

jobs:
  build:
    docker:
      - image: 325740378808.dkr.ecr.us-east-1.amazonaws.com/fsq-run:latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Run Tests
          command: make check
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  build-and-notify:
    jobs:
      - build:
          context:
            - slack
            - aws
