name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/acg/ubuntu1404-fsq-run:latest
      credentials:
        username: acg
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: make check

      - name: Report Status to Slack
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.CHECKS_SLACK_WEBHOOK_URL }}
          STATUS: ${{ job.status }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          test -z "$SLACK_WEBHOOK" || curl -f -d @- -H "Content-Type: application/json" "$SLACK_WEBHOOK" <<EOSLACKJSON
          {
            "text"         : "This is text: $STATUS",
            "attachments"  : [{
              "color"      : "#41aa58",
              "title"      : "This is the title: $STATUS",
              "title_link" : "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$PR_NUMBER"
            }]
          }
          EOSLACKJSON
