name: CI

on:
  pull_request:

permissions:
  actions: read

jobs:
  pr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/acg/ubuntu1404-fsq-run:latest
      credentials:
        username: acg
        password: ${{ secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: make check

      - name: Report Status to Slack
        if: always()
        uses: endcrawl/github-action-slack-notify-curl@master
        with:
          slack_webhook: ${{ secrets.CHECKS_SLACK_WEBHOOK_URL }}
